### ISSUE TITLE
“Property 'neo' does not exist on type 'Window & typeof globalThis'.ts(2339)”

### ISSUE THREAD

**Issue by robliou** [neo-ngd/neo-dapi-monorepo#1]
Hello,

I am trying to follow the tutorial on the Readme page. The goal is to utilize BaseDapi in my app.

My code looks like the following:

```
import { BaseDapi } from '@neongd/neo-dapi';

export const demo =() => {
    const dapi = new BaseDapi(window.neo);
 return (
      dapi,
     
    );
  } 
```
However, I get a red underline under '.neo' with the following error: “Property 'neo' does not exist on type 'Window & typeof globalThis'.ts(2339)”

This error is still there if I change to 'window.onegate', etc. 

Any idea why this error is showing up and how to fix?

Thanks,

Rob

**Comment by liuqiang1357** [comment]
This is a TypeScript error message indicating that the default window object does not have a 'neo' property. 

To resolve this error, you can add a declaration in the module where you need to use this property.

```
declare const window: Window & {
  neo?: Provider;
};
```

Alternatively, you can add this declaration to a global declaration file that can be used throughout your application.

```
interface Window {
  neo?: Provider;
}
```
